# Generated by Django 3.2 on 2024-01-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='user',
        ),
    ]
