# Generated by Django 3.2 on 2024-01-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0005_coment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
