# Generated by Django 3.2 on 2024-01-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0006_alter_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.AddField(
            model_name='review',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
