# Generated by Django 3.2 on 2024-01-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0007_auto_20240117_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='category',
            field=models.CharField(choices=[('art', 'イラスト'), ('handmade', 'ハンドメイド'), ('movie', '動画'), ('game', 'ゲーム')], default='なし', max_length=10),
        ),
    ]
