# Generated by Django 3.2 on 2024-01-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0008_alter_coment_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coment',
            old_name='thumbnail',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='coment',
            name='category',
            field=models.CharField(choices=[('art', 'イラスト'), ('handmade', 'ハンドメイド'), ('movie', '動画'), ('game', 'ゲーム')], max_length=10),
        ),
    ]
