# Generated by Django 3.2 on 2024-01-25 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snsapp', '0012_follow_like_post_repost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='target_post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='target_post',
        ),
        migrations.AddField(
            model_name='coment',
            name='likes',
            field=models.ManyToManyField(related_name='comment_likes', through='snsapp.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='coment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='snsapp.coment'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
