# Generated by Django 3.2 on 2024-01-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0013_auto_20240125_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='likes',
        ),
    ]
