# Generated by Django 3.2 on 2024-01-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0014_remove_coment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='coment',
            new_name='comment',
        ),
    ]
