# Generated by Django 3.2 on 2024-01-26 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snsapp', '0015_rename_coment_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='likes',
            field=models.ManyToManyField(related_name='comment_likes', through='snsapp.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
