# Generated by Django 3.2 on 2024-01-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0017_auto_20240126_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='user_record',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
