# Generated by Django 3.2 on 2024-01-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0019_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='user_record',
            field=models.TextField(blank=True, null=True),
        ),
    ]
