# Generated by Django 3.2 on 2024-01-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0020_alter_coment_user_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='category',
            field=models.CharField(choices=[('art', 'イラスト'), ('handmade', 'ハンドメイド'), ('movie', '動画'), ('game', 'ゲーム')], default='テキスト', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=models.TextField(blank=True, default='こんにちは', max_length=100, null=True),
        ),
    ]
