# Generated by Django 3.2 on 2024-01-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0021_auto_20240130_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='category',
            field=models.CharField(choices=[('text', 'テキスト'), ('art', 'イラスト'), ('handmade', 'ハンドメイド'), ('movie', '動画'), ('game', 'ゲーム')], default='テキスト', max_length=10),
        ),
    ]
