# Generated by Django 3.2 on 2024-02-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0023_alter_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='user_record',
            field=models.TextField(blank=True, default='1', null=True),
        ),
    ]
