# Generated by Django 3.2 on 2024-02-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0026_reply_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.AddField(
            model_name='reply',
            name='comment_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
